const CHANNELS=['ALL','SOMA','ARCANA','APPETITE','SIGNAL LAB','VISUAL CORTEX','THE PULSE','TERRA','VERDANT','IGNITION','OBJECTS OF DESIRE','EROS INDEX'];
const DIR={N:{x:0,y:-1,label:'FUTURE / SIGNAL',cats:['SIGNAL LAB','IGNITION']},NE:{x:.707,y:-.707,label:'DESIGN / STYLE',cats:['VISUAL CORTEX','APPETITE']},E:{x:1,y:0,label:'DESIRE / PRODUCTS',cats:['OBJECTS OF DESIRE','APPETITE']},SE:{x:.707,y:.707,label:'EROS / NIGHTLIFE',cats:['EROS INDEX','APPETITE']},S:{x:0,y:1,label:'BODY / SOMA',cats:['SOMA','EROS INDEX']},SW:{x:-.707,y:.707,label:'ARCANA / INNER WORLD',cats:['ARCANA','SOMA']},W:{x:-1,y:0,label:'WORLD / PULSE',cats:['THE PULSE','IGNITION']},NW:{x:-.707,y:-.707,label:'EARTH / NATURE',cats:['TERRA','VERDANT']}};
const VEC={'SIGNAL LAB':{x:0,y:-1},IGNITION:{x:-.35,y:-.94},'VISUAL CORTEX':{x:.707,y:-.707},'OBJECTS OF DESIRE':{x:1,y:0},APPETITE:{x:.92,y:.38},'EROS INDEX':{x:.707,y:.707},SOMA:{x:0,y:1},ARCANA:{x:-.707,y:.707},'THE PULSE':{x:-1,y:0},TERRA:{x:-.707,y:-.707},VERDANT:{x:-.82,y:-.57}};
const OFF={N:[0,-72],NE:[56,-56],E:[72,0],SE:[56,56],S:[0,72],SW:[-56,56],W:[-72,0],NW:[-56,-56],CENTER:[0,18]};
const $=s=>document.querySelector(s),MAX_AGE=24,SNAP_MS=320;
const S={items:[],active:'ALL',eros:false,mode:null,demo:false,current:null,nav:{x:0,y:0},dir:'CENTER',last:0,preview:null,focus:null,timelineDir:null,timelineStrength:0,history:[],historyHydrated:false,seen:Object.fromEntries(Object.keys(DIR).map(k=>[k,[]])),mem:JSON.parse(localStorage.getItem('sapio:memory')||'[]'),likes:JSON.parse(localStorage.getItem('sapio:likes')||'[]'),device:null};
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function age(d){const t=new Date(d).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):0}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function norm(v){const m=Math.hypot(v.x,v.y)||1;return{x:v.x/m,y:v.y/m}}
function hash(x=''){let h=0;for(const c of x){h=((h<<5)-h)+c.charCodeAt(0);h|=0}return Math.abs(h)}
function chicagoHour(){return +new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'2-digit',hour12:false}).format(new Date())}
function noct(){return S.mode===null?(chicagoHour()>=19||chicagoHour()<5):S.mode}
function erosOn(){return S.eros||noct()}
function saved(id){return S.mem.some(x=>x.id===id)}function liked(id){return S.likes.some(x=>x.id===id)}
function device(){if(S.device)return S.device;let id=localStorage.getItem('sapio:device-id');if(!id){id=crypto.randomUUID?.()||`sapio-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('sapio:device-id',id)}return S.device=id}
function localKey(){return`sapio:history:${device()}`}
function persistLocal(e){try{const a=JSON.parse(localStorage.getItem(localKey())||'[]').filter(x=>x?.id!==e.id);localStorage.setItem(localKey(),JSON.stringify([...a,e].slice(-30)))}catch{}}
async function persist(e){persistLocal(e);try{await fetch('/api/history',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId:device(),entry:e})})}catch{}}
function snapshot(i){return{id:i.id,title:i.title,summary:i.summary||'',url:i.url||'',categories:i.categories||[],primaryCategory:i.primaryCategory||'IGNITION',score:i.score||50,stage:i.stage||'WHISPER',velocity:i.velocity,sourceEdge:i.sourceEdge,evidenceQuality:i.evidenceQuality,sources:i.sources||1,sourceNames:i.sourceNames||[],publisher:i.publisher||'',publishedAt:i.publishedAt,sourceImage:i.sourceImage||null,image:i.image||null,eros:i.eros||i.primaryCategory==='EROS INDEX'}}
function retained(){return[...S.mem,...S.likes].map(x=>x.item).filter(Boolean)}
function all(){const live=S.items.filter(i=>S.demo||age(i.publishedAt)<MAX_AGE||saved(i.id)||liked(i.id)),m=new Map();[...live,...retained()].forEach(i=>i?.id&&!m.has(i.id)&&m.set(i.id,i));return[...m.values()]}
function base(i){return erosOn()||!(i.eros||i.primaryCategory==='EROS INDEX')}
function visible(i){return base(i)&&(S.active==='ALL'||i.primaryCategory===S.active||i.categories?.includes(S.active))}
function affinity(c){return Math.min(100,50+(S.mem.filter(x=>x.category===c).length+S.likes.filter(x=>x.category===c).length*.5)*8)}
function rank(i){return(i.score||50)*.75+affinity(i.primaryCategory)*.25}
function img(i){if(i.sourceImage)return i.sourceImage;if(i.image&&!String(i.image).startsWith('assets/'))return i.image;const a=hash(i.id||i.title)%360,b=(a+75)%360;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 750"><defs><linearGradient id="g"><stop stop-color="hsl(${a} 70% 55%)"/><stop offset="1" stop-color="hsl(${b} 72% 30%)"/></linearGradient></defs><rect width="1200" height="750" fill="url(#g)"/><circle cx="950" cy="160" r="240" fill="rgba(255,255,255,.13)"/></svg>`;return`data:image/svg+xml,${encodeURIComponent(svg)}`}
function ivec(i){let x=0,y=0,n=0;[...(i.categories||[]),i.primaryCategory].filter(Boolean).forEach(c=>{if(VEC[c]){x+=VEC[c].x;y+=VEC[c].y;n++}});if(n)return norm({x,y});const a=(hash(i.id||i.title)%360)*Math.PI/180;return{x:Math.cos(a),y:Math.sin(a)}}
function nearest(v){let k='N',best=-9;for(const[d,z]of Object.entries(DIR)){const q=v.x*z.x+v.y*z.y;if(q>best){best=q;k=d}}return k}
function dstate(){const m=Math.hypot(S.nav.x,S.nav.y);if(m<.2)return{key:null,label:'CENTER / BALANCED',strength:0};const k=nearest(norm(S.nav));return{key:k,label:DIR[k].label,strength:clamp(m/7,0,1)}}
function list(){return all().filter(visible).sort((a,b)=>rank(b)-rank(a))}
function current(){const a=list();if(!a.length)return null;let i=a.find(x=>x.id===S.current);if(!i){i=a[0];S.current=i.id;S.dir='CENTER'}return i}
function dscore(i,k){const v=ivec(i),d=DIR[k],dot=v.x*d.x+v.y*d.y,cats=new Set([...(i.categories||[]),i.primaryCategory]),bonus=d.cats.some(c=>cats.has(c))?18:0,ds=dstate();return rank(i)+dot*40+bonus+(ds.key===k?ds.strength*Math.max(0,dot)*28:0)-Math.min(18,age(i.publishedAt)*.35)}
function peek(k){return list().filter(x=>x.id!==S.current).sort((a,b)=>dscore(b,k)-dscore(a,k))[0]||null}
function next(k){const a=list().filter(x=>x.id!==S.current).sort((x,y)=>dscore(y,k)-dscore(x,k)),seen=S.seen[k];const n=a.find(x=>!seen.includes(x.id))||a[0]||null;if(n)S.seen[k]=[...seen.filter(id=>id!==n.id),n.id].slice(-48);return n}
function renderMode(){const n=noct();document.documentElement.classList.toggle('nocturne',n);$('#modeToggle').textContent=S.mode===null?`NOCTURNE ${n?'ON':'AUTO'}`:`NOCTURNE ${n?'ON':'OFF'}`;$('#modeLabel').textContent=n?'SAPIO // NOCTURNE':'DAY / CULTURAL INTELLIGENCE';$('#erosToggle').textContent=!S.eros&&n?'EROS AUTO':erosOn()?'EROS ON':'EROS OFF'}
function renderChannels(){const a=all().filter(base),counts={ALL:a.length};CHANNELS.slice(1).forEach(c=>counts[c]=a.filter(i=>i.primaryCategory===c||i.categories?.includes(c)).length);$('#categoryRail').innerHTML=CHANNELS.filter(c=>erosOn()||c!=='EROS INDEX').map(c=>`<button class="chip ${S.active===c?'active':''}" data-c="${esc(c)}">${esc(c)} <span>${counts[c]||0}</span></button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{S.active=b.dataset.c;S.current=null;S.history=[];renderAll()})}
function renderVector(){const d=dstate();$('#vectorLabel').textContent=d.label;$('#vectorDepth').textContent=`${Math.round(d.strength*100)}% DIRECTIONAL`;document.querySelectorAll('.compass-btn').forEach(b=>b.classList.toggle('active',b.dataset.dir===d.key))}
function renderPeeks(){const h=$('#directionPeeks');h.innerHTML=Object.keys(DIR).map(k=>[k,peek(k)]).filter(x=>x[1]).map(([k,i])=>`<button class="direction-peek peek-${k.toLowerCase()}" data-d="${k}" title="${esc(DIR[k].label)}: ${esc(i.title)}"><img src="${esc(img(i))}" alt=""><span><b>${k}</b>${esc(i.title)}</span></button>`).join('');h.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();move(b.dataset.d)})}
function renderHistory(){const b=$('#snapBackBtn');b.disabled=!S.history.length;const r=S.history.slice(-5);$('#snapTrail').innerHTML=r.length?r.map((e,j)=>`<button class="crumb" data-i="${S.history.length-r.length+j}" title="${esc(e.title)}">${esc(e.title)}</button>`).join(''):'<span class="trail-empty">NO HISTORY YET</span>';document.querySelectorAll('.crumb').forEach(b=>b.onclick=()=>restore(+b.dataset.i))}
function card(){const i=current();if(!i){$('#spatialWorld').innerHTML='<div class="map-empty">NO FRESH SIGNALS IN THIS CHANNEL</div>';$('#directionPeeks').innerHTML='';return}const lane=nearest(ivec(i)),o=OFF[S.dir]||OFF.CENTER;$('#spatialWorld').innerHTML=`<article class="spatial-card solo snap-enter" style="--enter-x:${o[0]}px;--enter-y:${o[1]}px" tabindex="0"><div class="spatial-image"><img src="${esc(img(i))}" alt="${esc(i.title)}"><span>${esc(i.stage||'SIGNAL')}</span></div><div class="spatial-body"><div class="spatial-meta">${esc(i.primaryCategory||'SIGNAL')} · ${Math.round(age(i.publishedAt))}H · ${i.sources||1} SOURCES</div><h3>${esc(i.title)}</h3><p class="solo-summary">${esc(i.summary||'No summary available.')}</p><div class="solo-direction">COMPASS LANE · ${esc(DIR[lane].label)}</div><div class="spatial-foot"><span>${saved(i.id)?'♥ SAVED':liked(i.id)?'♥ LIKED':'CLICK FOR PREVIEW'}</span><span>SCROLL TO SNAP</span></div></div></article>`;const c=$('.spatial-card');c.onclick=()=>preview(i);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();preview(i)}};renderPeeks()}
function push(i){if(!i)return;const e={id:i.id,title:i.title,nav:{...S.nav},dir:S.dir};if(S.history.at(-1)?.id!==e.id)S.history=[...S.history,e].slice(-12)}
function move(k){const d=DIR[k],i=current();if(!d||!i)return;push(i);S.nav={x:clamp(S.nav.x+d.x,-10,10),y:clamp(S.nav.y+d.y,-10,10)};const n=next(k);if(n)S.current=n.id;S.dir=k;if(n)persist({id:n.id,title:n.title,nav:{...S.nav},dir:k,viewedAt:new Date().toISOString()});renderAll()}
function restore(n){const e=S.history[n];if(!e)return;S.history=S.history.slice(0,n);S.current=e.id;S.nav=e.nav||{x:0,y:0};S.dir=e.dir||'CENTER';renderAll()}
function recenter(){S.nav={x:0,y:0};S.current=null;S.dir='CENTER';S.history=[];renderAll()}
function preview(i){if(!i)return;S.preview=i;$('#previewPanel').classList.add('open');$('#previewPanel').setAttribute('aria-hidden','false');$('#previewScrim').hidden=false;$('#previewMedia').innerHTML=`<img src="${esc(img(i))}" alt="${esc(i.title)}">`;$('#previewMeta').innerHTML=`<span>${esc(i.primaryCategory)}</span><span class="stage">${esc(i.stage||'WHISPER')}</span><span>${i.sources||1} SOURCES</span><span>${Math.round(age(i.publishedAt))}H</span>`;$('#previewTitle').textContent=i.title;$('#previewSummary').textContent=i.summary||'No summary available.';$('#previewMetrics').innerHTML=`<div class="metric"><b>${i.velocity??'—'}</b><span>VELOCITY</span></div><div class="metric"><b>${i.sourceEdge??'—'}</b><span>SOURCE EDGE</span></div><div class="metric"><b>${i.evidenceQuality??'—'}</b><span>EVIDENCE</span></div>`;$('#previewSave').textContent=saved(i.id)?'♥ SAVED':'♡ MEMORY';$('#previewLike').textContent=liked(i.id)?'♥ LIKED':'♡ LIKE';$('#previewSource').hidden=!i.url;if(i.url)$('#previewSource').href=i.url}
function closePreview(){S.preview=null;$('#previewPanel').classList.remove('open');$('#previewPanel').setAttribute('aria-hidden','true');$('#previewScrim').hidden=true}
const STOP=new Set('the a an and or but for with from into over under about this that these those of to in on at by is are was were be been being as it its their our your new how why what who when where more most after before'.split(' '));function tok(s=''){return new Set(String(s).toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))}function sim(a,b){const A=tok(a),B=tok(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>B.has(x)&&n++);return n/new Set([...A,...B]).size}
function tboost(i){if(!S.timelineDir)return 0;const d=DIR[S.timelineDir],v=ivec(i),dot=v.x*d.x+v.y*d.y,c=new Set([...(i.categories||[]),i.primaryCategory]);return dot*28+(d.cats.some(x=>c.has(x))?14:0)+S.timelineStrength*Math.max(0,dot)*22}
function fscore(i,f){if(!f)return rank(i)+tboost(i);const A=new Set(i.categories||[]),B=new Set(f.categories||[]);let n=0;A.forEach(x=>B.has(x)&&n++);return rank(i)*.35+n/Math.max(1,new Set([...A,...B]).size)*45+sim(`${i.title} ${i.summary||''}`,`${f.title} ${f.summary||''}`)*35+Math.max(0,20-age(i.publishedAt)*.6)+tboost(i)}
function timeline(){if($('#timelineView').hidden)return;const f=S.focus,d=S.timelineDir?DIR[S.timelineDir].label:null,a=all().filter(i=>visible(i)&&(!f||i.id!==f.id)).sort((x,y)=>fscore(y,f)-fscore(x,f)).slice(0,40);$('#timelineTitle').textContent=f?f.title:d?`${d} signals`:'All signals';$('#timelineCopy').textContent=f?(d?`Signals increasingly related to this card, with emphasis on ${d.toLowerCase()}.`:`Signals increasingly related to ${f.primaryCategory}.`):(d?`Timeline emphasis inherited from your ${d.toLowerCase()} exploration.`:'Standard vertical timeline.');$('#feed').innerHTML=a.map(i=>`<article class="timeline-card" data-id="${esc(i.id)}"><div class="timeline-media"><img src="${esc(img(i))}" alt="${esc(i.title)}"></div><div class="timeline-body"><div class="meta"><span>${esc(i.primaryCategory)}</span><span class="stage">${esc(i.stage||'WHISPER')}</span><span>${Math.round(age(i.publishedAt))}H</span></div><h2>${esc(i.title)}</h2><p>${esc(i.summary||'')}</p><div class="actions"><button class="ghost p">PREVIEW</button><button class="ghost s">${saved(i.id)?'♥ SAVED':'♡ MEMORY'}</button><button class="ghost l">${liked(i.id)?'♥ LIKED':'♡ LIKE'}</button>${i.url?`<a class="source-link" href="${esc(i.url)}" target="_blank">SOURCE ↗</a>`:''}</div></div></article>`).join('')||'<div class="feed-end">NO RELATED FRESH SIGNALS YET</div>';document.querySelectorAll('.timeline-card').forEach(c=>{const i=all().find(x=>x.id===c.dataset.id);c.querySelector('.p').onclick=()=>preview(i);c.querySelector('.s').onclick=()=>save(i);c.querySelector('.l').onclick=()=>like(i)})}
function enterTimeline(i=current()){const d=dstate();S.focus=i;S.timelineDir=d.key||(S.dir!=='CENTER'?S.dir:null);S.timelineStrength=d.strength||(S.timelineDir?.72:0);$('#mapView').hidden=true;$('#timelineView').hidden=false;$('#mapBtn').classList.remove('active');$('#timelineBtn').classList.add('active');$('#heroTitle').textContent='Follow the thread.';$('#heroCopy').textContent=S.timelineDir?'This timeline inherits the exact direction you were exploring.':'Standard vertical reading mode.';closePreview();timeline();scrollTo({top:0,behavior:'smooth'})}
function enterMap(){$('#mapView').hidden=false;$('#timelineView').hidden=true;$('#mapBtn').classList.add('active');$('#timelineBtn').classList.remove('active');$('#heroTitle').textContent='One signal at a time.';$('#heroCopy').textContent='Scroll, swipe, use the compass, or tap arrow keys. Each move snaps the next card from that direction.';renderAll()}
function save(i){const n=S.mem.findIndex(x=>x.id===i.id);n>=0?S.mem.splice(n,1):S.mem.unshift({id:i.id,title:i.title,url:i.url||'',category:i.primaryCategory,savedAt:new Date().toISOString(),item:snapshot(i)});localStorage.setItem('sapio:memory',JSON.stringify(S.mem));renderMemory();renderAll();if(S.preview?.id===i.id)preview(i)}
function like(i){const n=S.likes.findIndex(x=>x.id===i.id);n>=0?S.likes.splice(n,1):S.likes.unshift({id:i.id,category:i.primaryCategory,likedAt:new Date().toISOString(),item:snapshot(i)});localStorage.setItem('sapio:likes',JSON.stringify(S.likes));renderAll();if(S.preview?.id===i.id)preview(i)}
function renderMemory(){$('#memoryCount').textContent=S.mem.length;$('#memoryList').innerHTML=S.mem.length?S.mem.map(m=>`<div class="memory-item"><button data-id="${esc(m.id)}">${esc(m.title)}</button><small>${esc(m.category)} · ${new Date(m.savedAt).toLocaleDateString()}</small></div>`).join(''):'<div class="feed-end">NOTHING SAVED YET</div>';document.querySelectorAll('.memory-item button').forEach(b=>b.onclick=()=>{const i=all().find(x=>x.id===b.dataset.id);if(i){drawer(false);preview(i)}})}
function drawer(on){$('#memoryDrawer').classList.toggle('open',on);$('#memoryDrawer').setAttribute('aria-hidden',on?'false':'true');$('#drawerScrim').hidden=!on}
function renderAll(){renderMode();renderChannels();renderVector();card();renderHistory();timeline()}
async function hydrate(){if(S.historyHydrated)return;S.historyHydrated=true;let a=[];try{const r=await fetch(`/api/history?device=${encodeURIComponent(device())}`,{cache:'no-store'});if(r.ok)a=(await r.json()).entries||[]}catch{}if(!a.length)try{a=JSON.parse(localStorage.getItem(localKey())||'[]')}catch{}const ok=a.filter(e=>all().some(i=>i.id===e.id));if(!ok.length)return;const c=ok.at(-1);S.history=ok.slice(0,-1).map(e=>({id:e.id,title:e.title,nav:e.nav||{x:0,y:0},dir:e.dir||'CENTER'})).slice(-12);S.current=c.id;S.nav=c.nav||{x:0,y:0};S.dir=c.dir||'CENTER'}
async function load(){let d=null;try{const r=await fetch('/api/feed',{cache:'no-store'});if(r.ok)d=await r.json()}catch{}if(!d)try{d=await(await fetch('data/sample.json')).json()}catch{d={demo:true,items:[]}}S.demo=!!d.demo;S.items=d.items||[];$('#liveDot').classList.toggle('live',!!d.live);$('#runText').textContent=d.live?`LIVE · ${S.items.filter(i=>age(i.publishedAt)<MAX_AGE).length} FRESH · SNAP EXPLORER`:`DEMO · ${S.items.length} CARDS`;await hydrate();renderAll()}
function setup(){const ok=localStorage.getItem('sapio:21plus')==='yes';$('#ageGate').hidden=ok;$('#enterBtn').onclick=()=>{localStorage.setItem('sapio:21plus','yes');$('#ageGate').hidden=true};$('#erosToggle').onclick=()=>{S.eros=!S.eros;if(!erosOn()&&S.active==='EROS INDEX')S.active='ALL';renderAll()};$('#modeToggle').onclick=()=>{const n=noct();S.mode=S.mode===null?!n:S.mode?false:null;renderAll()};$('#mapBtn').onclick=enterMap;$('#timelineBtn').onclick=()=>enterTimeline();$('#backToMap').onclick=enterMap;$('#memoryBtn').onclick=()=>drawer(true);$('#closeMemory').onclick=()=>drawer(false);$('#drawerScrim').onclick=()=>drawer(false);$('#closePreview').onclick=closePreview;$('#previewScrim').onclick=closePreview;$('#previewTimeline').onclick=()=>enterTimeline(S.preview||current());$('#previewSave').onclick=()=>S.preview&&save(S.preview);$('#previewLike').onclick=()=>S.preview&&like(S.preview);$('#recenterBtn').onclick=recenter;$('#compassCenter').onclick=recenter;$('#snapBackBtn').onclick=()=>S.history.length&&restore(S.history.length-1);document.querySelectorAll('.compass-btn').forEach(b=>b.onclick=()=>move(b.dataset.dir));let swipe=null,v=$('#spatialViewport');v.onwheel=e=>{e.preventDefault();if(Date.now()-S.last<SNAP_MS)return;S.last=Date.now();const dx=e.deltaX,dy=e.deltaY;if(Math.abs(dx)<6&&Math.abs(dy)<6)return;move(nearest(norm({x:dx,y:dy}))) };v.onpointerdown=e=>swipe={x:e.clientX,y:e.clientY};v.onpointerup=e=>{if(!swipe)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.hypot(dx,dy)>34)move(nearest(norm({x:-dx,y:-dy})))};v.onkeydown=e=>{const k={ArrowUp:'N',ArrowDown:'S',ArrowLeft:'W',ArrowRight:'E',q:'NW',e:'NE',z:'SW',c:'SE'}[String(e.key).toLowerCase()==='arrowup'?'ArrowUp':String(e.key).toLowerCase()==='arrowdown'?'ArrowDown':String(e.key).toLowerCase()==='arrowleft'?'ArrowLeft':String(e.key).toLowerCase()==='arrowright'?'ArrowRight':String(e.key).toLowerCase()];if(k){e.preventDefault();move(k)}};document.addEventListener('keydown',e=>e.key==='Escape'&&(closePreview(),drawer(false)));renderMemory();load();setInterval(load,5*60*1000)}
setup();
